spring:
  profiles:
    active:
    - ExampleCreateThread
    - ExampleInheritThread
    - ExampleGuessingPassword
    - ExampleInterruptSleepingThread
    - ExampleInterruptLongComputationThread
    - ExampleInterruptDaemonThread
    - ExampleJoinThread
    - ExampleOptimizeLatency
